### ISSUE TITLE
PHP warning: Undefined array key "debug"

### ISSUE THREAD

**Issue by mediengaarage** [Sterc/SEOSuite#101]
In the error log file is the following error a thound times:
PHP warning: Undefined array key "debug" 
Level: Error
File: {core_path}components/seosuite/model/seosuite/seosuite.class.php
Line: 267

MODX 2.8.4
PHP 8.1.18
SEOSuite 2.0.6

**Comment by Bravens** [comment]
@mediengaarage This issue was fixed in SeoSuite 3.1.1, commit: [b4cfd18](https://github.com/Sterc/seosuite/commit/b4cfd18b191c4ac609a00ef6ede77c4695932b03).

Upgrade to latest version is recommended.
