### ISSUE TITLE
Invalid priority value in generated sitemap.xml

### ISSUE THREAD

**Issue by lapp** [Sterc/seosuite#12]
Hi to Sterc,

thanks for your great job guys with SEOSuite. I have found one bug in generated (using default chunks) sitemap.xml:
- **`<priority>normal</priority>` - string value "normal" is not valid, it should be decimal** (https://www.sitemaps.org/schemas/sitemap/0.9/sitemap.xsd)
- string value is saved in DB modx_seosuite_resource

Please, take a look at it.
Thanks a lot
Regards
Michal

**Comment by funkyduke** [comment]
I always get an error in my dashboard on Google. 

Invalid value for code.

See screenshot.
![afbeelding](https://user-images.githubusercontent.com/1769979/110398075-604a2b80-8073-11eb-96a3-52d52fd59b59.png)

**Comment by CarlPiper** [comment]
@funkyduke not sure if you did this already, but while it is still broken you could use the below tag:

`[[!SeoSuiteSitemap:replace=`<priority>high</priority>==<priority>1</priority>`:replace=`<priority>normal</priority>==<priority>0.5</priority>`:replace=`<priority>low</priority>==<priority>0.25</priority>`]]`

![image](https://user-images.githubusercontent.com/41297339/115037744-b27a3a00-9ec6-11eb-953e-20f5c782fcda.png)

**Comment by funkyduke** [comment]
> 
> 
> @funkyduke not sure if you did this already, but while it is still broken you could use the below tag:
> 
> `[[!SeoSuiteSitemap:replace=`high==1`:replace=`normal==0.5`:replace=`low==0.25`]]`
> 
> ![image](https://user-images.githubusercontent.com/41297339/115037744-b27a3a00-9ec6-11eb-953e-20f5c782fcda.png)

Thank you! This helped for now.

**Comment by getandyjones** [comment]
Any further on fixing this issue?

**Comment by NickBack** [comment]
Yup, this is still happening. Seems like it should be an easy fix? The workaround works.

I think the correct fix though is to completely remove the priority and changefreq tags and simplify that part of the SEO Suite.

Google completely ignores those tags in practice (as you can read here: https://developers.google.com/search/docs/advanced/sitemaps/build-sitemap ).

"Google ignores priority and changefreq values."

So the correct move here is to simplify our lives and removes those from the generation of the sitemap and from the modx manager UI.

**Comment by ilyautkin** [comment]
Fixed in 3.0.1
