### ISSUE TITLE
seosuite is not returning anything

### ISSUE THREAD

**Issue by funkyduke** [Sterc/seosuite#14]
I don't know what is going wrong, but I did the following and nothing is returned in my code on the website:

1) Install SEOsuite
2) choose upgrade SEOTab and SEOpro
3) remove SEOTab and SEOpro
4) seosuite.placeholder_plugin_enabled is enabled
5) cleared cache

Nothing happens. Only the sitemap works. Did I overlook something? Do I need to put something in the head? 

disabling seosuite.placeholder_plugin_enabled and put `[[!+ss.meta]]` or `[[!+ss_meta]]` also returns nothing.

Not clear to me what goes wrong.

Modx 2.8.1. PHP 7.4

**Comment by funkyduke** [comment]
OK, I got it working. But the documentation should be updated.

`        [[!SeoSuiteMeta? &toPlaceholders=`1`]]
        [[!+ss_meta]]`

This works with seosuite.placeholder_plugin_enabled disabled.

**Comment by ilyautkin** [comment]
Fixed. Thank you!
