### ISSUE TITLE
htmlentities in all fields, lang in HTML-tag is ignored

### ISSUE THREAD

**Issue by Netzfeld** [Sterc/seosuite#17]
Hi Sterc, thanks for this shiny new piece of an extra!
In source I'm getting htmlentities in the title and in all the metas.
ä gets &amp;auml;

**Comment by ilyautkin** [comment]
@Netzfeld thank you. In 3.1.3 `htmlentities` was replaced by `htmlspecialchars`. Now letters should display correct.
