### ISSUE TITLE
Permanent error in logs

### ISSUE THREAD

**Issue by pashajanx** [Sterc/seosuite#20]
**Summary**
Permanent error in logs:
`[2021-03-26 11:53:45] (ERROR @ ../components/seosuite/model/seosuite/seosuite.class.php : 778) PHP warning: trim() expects parameter 1 to be string, array given`

**Environment**
MODX 2.8.1-pl
SEO Suite 2.0.2-pl

**Comment by crimsonpixel** [comment]
These errors are also appearing for me:

[2021-05-18 10:58:21] (ERROR @ .../components/seosuite/model/seosuite/seosuite.class.php : 779) PHP warning: trim() expects parameter 1 to be string, array given

Environment
MODX 2.8.2-pl
SEO Suite 2.0.2-pl
PHP 7.4

**Comment by ilyautkin** [comment]
Fixed in https://github.com/Sterc/seosuite/pull/15
