### ISSUE TITLE
Broken image

### ISSUE THREAD

**Issue by wax100** [Sterc/seosuite#23]
![111](https://user-images.githubusercontent.com/4846064/114528956-2829a000-9c52-11eb-93e3-ae6109b0fb32.jpg)
After I upload image , select it, save page and refresh it - I get broken image. 
Image is from Custom media Souce. On frontend I also get broken image

**Comment by funkyduke** [comment]
https://github.com/Sterc/seosuite/issues/33

**Comment by bennyb** [comment]
Just had the same issue.  And the path in the generated tag doesn't include the media source path.  Got around it for the moment by using a quick custom snippet that splits up the path and hard codes the media source path in it.  Not ideal but works for now.
