### ISSUE TITLE
meta name\property 

### ISSUE THREAD

**Issue by wax100** [Sterc/seosuite#24]
If we use custom plugin we get 
`<meta name="og:image" content="LINK_TO_IMAGE" /> `
but correct should be 
`<meta property="og:image" content="LINK_TO_IMAGE" /> `

So all social meta tags should use PROPERTY instead of name. 
Will be good If U add this as custom feature

**Comment by funkyduke** [comment]
https://github.com/Sterc/seosuite/issues/16

**Comment by ilyautkin** [comment]
Fixed in https://github.com/Sterc/seosuite/pull/25
