### ISSUE TITLE
Can't install the component on most shared hosting

### ISSUE THREAD

**Issue by Semdevmaster** [Sterc/seosuite#27]
I keep getting an error during installation:
![photo_2021-04-21_15-06-17](https://user-images.githubusercontent.com/2706508/115551255-79b9d680-a2b3-11eb-83aa-3855697bc097.jpg)
The max limit for the index is 3072 bytes, but the table has a varhar field (2000)
It turns out that when encoding utf8mb4_unicode_ci, the limit is exceeded.
If the MySQL server is configured correctly, then the index should be truncated to 768, but this is not the case for most hosting companies.

**Comment by robcarey** [comment]
Same issue here. utf8_general_ci in my case.

**Comment by catchgit** [comment]
I get two issues with installing this package on our server:
![skrinsjott](https://user-images.githubusercontent.com/9208635/129694268-a5c3baaa-38d0-453c-94e2-aafe750f3eb2.jpg)

One is "could not create table modx_seosuite_redirect" with the reason: invalid default value for 'last_visit'. The default value is 0000-00-00 00:00:00.

The other is "could not create table modx_seosuite_url" with the reason: Specified key was too long; max key length is 3072 bytes.

The database is in utf8mb4_general_ci

**Comment by des-yogi** [comment]
I have the same error on every hosting where I have tried to install this package. I'm talking about version 2.0.6. Version 3 doesn't install on Modx 2.8.5 at all...

**Comment by ilyautkin** [comment]
Fixed in https://github.com/Sterc/seosuite/pull/107/commits/27175cf3a2010ef915e0ada8d4fba603748786da
