### ISSUE TITLE
Facebook image path not correct when using different media source

### ISSUE THREAD

**Issue by funkyduke** [Sterc/seosuite#33]
When the default media source is set to another directory in the system settings, f.e. assets/userfiles/, then the link to the image is wrong.

It must be:

`<meta property="og:image" content="https://www.website.com/assets/userfiles/galleries/23/14_8.jpg" />`

instead I get (when selecting the correct image in the backend):

`<meta property="og:image" content="https://www.website.com/galleries/23/14_8.jpg" />`

The assets/userfiles/ path is missing.

Modx 2.8.3. PHP 7.4.

![afbeelding](https://user-images.githubusercontent.com/1769979/121923627-6a975800-cd3b-11eb-8710-933744eb649b.png)

**Comment by ilyautkin** [comment]
Fixed in https://github.com/Sterc/seosuite/pull/35
