### ISSUE TITLE
system setting seosuite.disabled_templates not working correctly 

### ISSUE THREAD

**Issue by bennyb** [Sterc/seosuite#34]
If you put in a value under the system setting seosuite.disabled_templates it disables SEO suite for all resources that aren't using that template rather than disabling for the specified template ID.

**Comment by Demonstr8** [comment]
Check my answer https://github.com/Sterc/seosuite/issues/37#issuecomment-942136387

**Comment by BigBlockStudios** [comment]
@bennyb yea - this got me too, it actually works inverse to how it is documented - just put in all the templates you want the seo suite to use. (and omit) the ones you don't

the setting name "seosuite.disabled_templates" should probably be renamed to "seosuite.enabled_templates" and the documentation updated.

**Comment by Bravens** [comment]
Fixed in #72
