### ISSUE TITLE
SEOsuite not display the sitemap 

### ISSUE THREAD

**Issue by Ilja-developer** [Sterc/seosuite#39]
Just tried the amazing Seosuite. It’s been a bliss to see those extras work together. Thanks so much for putting it out.

So the problem I have is to display the sitemap correctly.

What i did:

1. Create a resource tpl empty
2. Uncheck cache and richtext
3. Put the snippet [[!SeoSuiteSitemap]] in content
4. Set the type to XML

But the result is: This XML file does not appear to have any style information associated with it. The document tree is shown below.
![sitemap](https://user-images.githubusercontent.com/29120151/133117768-2bc211ff-be97-4b48-b4c2-fbb73ad70aef.jpg)

**Comment by Demonstr8** [comment]
All you need to turn on checkbox show this page in sitemap (edit - > search tab -> sitemap) for all page
