### ISSUE TITLE
Canonical tag is formatted as a meta tag - wrongly

### ISSUE THREAD

**Issue by getandyjones** [Sterc/SEOSuite#43]
One thing I noticed is that it formats canonical links incorrectly. It outputs them as meta tags:

<meta name="canonical" content="https://www.domain.co.uk/" />

But they shouldn’t be meta tags - they should be output like this:

<link rel=”canonical” href=https://domain.co.uk/” />

Canonical tags need their own tpl.

**Comment by getandyjones** [comment]
`  $meta['_canonical'] = [
            'name'  => 'canonical',
            'value' => $canonicalUrl,
            'tpl'   => $tpl
        ];
`
The above needs to change to:
`
    $meta['_canonical'] = [
            'name'  => 'canonical',
            'value' => $canonicalUrl,
            'tpl'   => $tplLink
        ];
`
Then it works fine!

**Comment by bYemma** [comment]
Thank you @[getandyjones](https://github.com/getandyjones). I created a pull request with your fix.

**Comment by Bulkmaker** [comment]
Stiil not changed

**Comment by ilyautkin** [comment]
Fixed in 3.0.4
