### ISSUE TITLE
MODX 3 Image crashes page

### ISSUE THREAD

**Issue by toro-terminator** [Sterc/SEOSuite#45]
In MODX 3 pre release adding a facebook image in the tab or in the system setting crashes the page. 

Error Log says the following

```
[2021-11-18 14:43:43] (ERROR @ /www/core/vendor/xpdo/xpdo/src/xPDO/xPDO.php : 786) modMediaSource::load() is not a valid static method.
```

**Comment by thomasmayerfoss** [comment]
This also happens in MODX 2.8.3 for me, on multiple installations, so it seems it’s not just a MODX 3 issue.

**Comment by ilyautkin** [comment]
Fixed in https://github.com/Sterc/seosuite/pull/35
