### ISSUE TITLE
MODX 3 : margin to right of icon in tabs messes up trash icon spacing

### ISSUE THREAD

**Issue by SnowCreative** [Sterc/SEOSuite#48]
In your CSS, this line:

```
.x-btn-text .icon, .x-tab-strip-text .icon {
    margin-right: 8px;
}
```

puts spacing to the right of the social icons in the Social tab, but it also puts a margin to the right of the trash icon in the main MODX editing button bar:
![Screen Shot 2021-12-12 at 11 48 45 AM](https://user-images.githubusercontent.com/2528374/145721601-0c17b650-3653-41a1-b17b-e5ee57588a15.png)

I suggest changing your CSS to make it specific to the tab area instead of globally — something like this:

```
.x-tab-panel-header .x-btn-text .icon, .x-tab-panel-header .x-tab-strip-text .icon {
    margin-right: 8px;
}
```

Adding ".x-tab-panel-header" in front of the classes fixes the problem, although with ".x-tab-strip-text .icon" this still makes the style applied to any other extras that may use icons in the side tabs. It also applies to the trash can in the modx-leftbar-tabpanel, but fortunately it gets overridden by one of the MODX manager CSS declarations.

**Comment by Bravens** [comment]
This has been fixed in the latest commit: [d71dbdaa7f79918906344e7514b07c6a3ae9589b](https://github.com/Sterc/seosuite/commit/d71dbdaa7f79918906344e7514b07c6a3ae9589b). 
Thank you for your suggestion.
