### ISSUE TITLE
PHP warning: Undefined array key "debug"

### ISSUE THREAD

**Issue by bYemma** [Sterc/SEOSuite#49]
This line generates a warning `PHP warning: Undefined array key "debug"`

https://github.com/Sterc/seosuite/blob/0ad3b1cedc4ae8d148ce01389774157fec2fc051/core/components/seosuite/model/seosuite/seosuite.class.php#L267

Maybe you can give this property a default value in constructor to prevent the warning?

**Comment by Hori76** [comment]
Same warning with PHP 8.0.15, not with PHP 7.4.27
