### ISSUE TITLE
Redactor 3.0 Issues

### ISSUE THREAD

**Issue by crecorn** [Sterc/seosuite#5]
I have installed this on two sites and both times it caused issues with Redactor 3.0.

All formatting within Redactor is removed or set to "p" tags.

When switching to code view CodeMirror is not available and switching back removes formatting.

Thanks for all the work on this. I was paying for this extra through modmore but I see that it's no longer available there.

**Comment by Oetzie** [comment]
@crecorn see my comment for issue 4 https://github.com/Sterc/seosuite/issues/4

**Comment by sdrenth** [comment]
@crecorn I've released v2.0.2 which resolves this issue.
