### ISSUE TITLE
Error during installation of 3.0.0-beta into MODX3 site.

### ISSUE THREAD

**Issue by SnowCreative** [Sterc/SEOSuite#50]
Just installed the 3.0.0-beta update into my MODX 3.0.0-beta1 installation. Installation completed, but ended with this error:

Could not load class: modTransportPackage from mysql.modtransportpackage
Could not get table name for class:
Error 42000 executing statement: Array ( [0] => 42000 [1] => 1064 [2] => You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'AS `latestPackage` WHERE `latestPackage`.`package_name` = `modTransp' at line 3 )

**Comment by Esger** [comment]
Modx 3.0.1 ModxCloud 
Updating to 3.0.4-beta same error:
Could not load class: modTransportPackage from mysql.modtransportpackage
Could not get table name for class:
```
Error 42000 executing statement: Array ( [0] => 42000 [1] => 1064 [2] => You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'AS `latestPackage` WHERE `latestPackage`.`package_name` = `modTransp' at line 3 )
```

**Comment by crimsonpixel** [comment]
Same problem here - installs with error and then doesn't work.  Using MODX 3.0.1 and SeoSuite version 3.0.4 beta.  This was a fresh install for both MODX and SeoSuite.  Not an upgrade.

Error message on load

`Could not load class: modTransportPackage from mysql.modtransportpackage
Could not get table name for class:
Error 42000 executing statement: Array ( [0] => 42000 [1] => 1064 [2] => You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'AS `latestPackage` WHERE `latestPackage`.`package_name` = `modTra...' at line 3 ) `

**Comment by ilyautkin** [comment]
SeoSuite 3.1.3
MODX 3.0.3

Installation correct.
