### ISSUE TITLE
placeholders not working after migration from SEO TAB

### ISSUE THREAD

**Issue by getandyjones** [Sterc/SEOSuite#54]
So I’ve used SEO Sutie a handful of times, all great.
I prefer using the placeholders:

```
[[!+ss_meta.meta_title]]
[[!+ss_meta.meta_description]]
[[!+ss_meta.robots]]
[[!+ss_meta.canonical]]
[[!+ss_meta.alternates]]
[[!+ss_meta.og_title]]
[[!+ss_meta.og_description]]
[[!+ss_meta.og_image]]
[[!+ss_meta.og_image_alt]]
[[!+ss_meta.og_type]]
[[!+ss_meta.twitter_site]]
[[!+ss_meta.twitter_title]]
[[!+ss_meta.twitter_description]]
[[!+ss_meta.twitter_image]]
[[!+ss_meta.twitter_image_alt]]
[[!+ss_meta.twitter_card]]
```

so i can have full control over the output, rather than using this snippet:

`[[!SeoSuiteMeta]]`

On this occasion, I ‘migrated’ from SEO Pro to SEO Suite in the installer.

I’m not sure if this has done something different, but the placeholders don’t work - I can only bring in the meta tag using the snippet.

I’ve tried everything I can think of - turned on/off the system setting:
seosuite.placeholder_plugin_enabled

Cleared the core/cache
Logged out and in again.

I can only assume it’s related to the migration, as opposed to a standard install - although I have also reinstalled the extra.

**Comment by joeke** [comment]
@getandyjones This should be fixed in the more recent versions, can you confirm this?
