### ISSUE TITLE
Return all placeholders is empty on toPlaceholders

### ISSUE THREAD

**Issue by azeller** [Sterc/seosuite#6]
When running the snippet with toPlaceholders switched on, all fields that have been set will be rendered when triggered individually, however, the placeholder allegedly holding all placeholders is empty.

**Comment by sdrenth** [comment]
@azeller Can you try with `ss_meta`? It looks like the placeholder stated in the readme is wrong. If that works, I'll change it right away in the readme

**Comment by crecorn** [comment]
This needs fixed on the github homepage readme also.

**Comment by ilyautkin** [comment]
Using `toPlaceholder` fixed in readme and in last version.
