### ISSUE TITLE
changefreq value issues

### ISSUE THREAD

**Issue by Jako** [Sterc/SEOSuite#60]
A changefreq value of `hourly` returns `0.5` in the changefreq placeholder. The changefreq value of `always` returns `1` in the changefreq placeholder. I have not checked this further, but at least the two values are definitely wrong.

These values can be selected in the dropdown in the Search engine -> Sitemap tab of a resource.

**Comment by ilyautkin** [comment]
@Jako, in `3.0.5` this should be fixed
