### ISSUE TITLE
Default meta values when no SeoSuiteResource object

### ISSUE THREAD

**Issue by joeke** [Sterc/SEOSuite#63]
When there is no `SeoSuiteResource` object for a resource, the `ss_meta` placeholder does not return anything due to the `return false` in the `seosuiteMeta` method in the `SeoSuiteSnippets` class. I feel this return false could be removed.

**Comment by ilyautkin** [comment]
@joeke, this should be fixed in new release `3.0.5`. It already in MODX repository.
