### ISSUE TITLE
disabled_templates not working

### ISSUE THREAD

**Issue by jmacdonald-spectacle** [Sterc/SEOSuite#68]
MODX 3.0.1, 3.0.2-dev; SEOSuite 3.0.4-beta

disabled_templates aren't working correctly:
- left empty: shows on all templates (correct)
- template(s) entered don't show but others do.

Frankly I prefer this behaviour as I'd rather opt-in than out, but it doesn't do what it's supposed to.

**Comment by toro-terminator** [comment]
Similar experience. The result is backwards. I enter ID "5" to be disabled, but ID 5 is the only template with the plugin.

**Comment by Bravens** [comment]
Fixed in #72

**Comment by Bravens** [comment]
Fixed in #72

**Comment by rthrash** [comment]
This probably needs to be backported to the 2.0.x branch as it's broken there, too.

**Comment by rthrash** [comment]
@gpsietzema @joeke ^

Specifically this which fixes it: 

![image](https://github.com/Sterc/seosuite/assets/234237/ddd2a499-447d-453a-ab8e-2232e7f9416b)
