### ISSUE TITLE
MODX 3.0.1 compatible? 

### ISSUE THREAD

**Issue by sonicpunk** [Sterc/SEOSuite#71]
Upgraded a current project from MODX 2.8.4 to MODX3.0.1 and this tool does not work as expected.

- sitemaps do not get written to output
- metatags do not get written to output
- CMS UI does not get shown

**Comment by sonicpunk** [comment]
@gpsietzema What is the best way for us to test out the MODX3 refactor branch? Can you provide a transport package?

**Comment by sonicpunk** [comment]
Is this the most up-to-date? [seosuite-3.0.4-beta.transport.zip](https://github.com/Sterc/seosuite/blob/modx3-refactor/_packages/seosuite-3.0.4-beta.transport.zip)

**Comment by sonicpunk** [comment]
@gpsietzema sorry, just checked and we already have the 3.0.4 beta installed and we are having the same issues.

**Comment by gpsietzema** [comment]
@sonicpunk new build is likely coming next week.

**Comment by DESIGNfromWITHIN** [comment]
Would be great to use this on MODX 3.0.2

**Comment by joeke** [comment]
@sonicpunk Should be fully compatible with MODX 3 with latest release now: https://modx.com/extras/package/seosuite. 
Feel free to reopen this issue or create a new one if you still encounter issues with the latest version.
