### ISSUE TITLE
SeoSuite Issues

### ISSUE THREAD

**Issue by MrRoco** [Sterc/SEOSuite#73]
- On install, create the allround seosuite permission is not .
- When logged in to the manager with a user which has limited permission opening a page on frontend results in 500 error. seosuitesnippets.class.php > getAlternateLinks function > Line: 374, check if ctx is set.
- Make sure redirects are 301 redirect by default.
- Check url migration from SeoTab.
- Disable seoTab on install.
- Sitemap: Check values & make sure url are set.

**Comment by ilyautkin** [comment]
@MrRoco 

- All permissions created on install
- Added check for `$ctx` in `getAlternateLinks`
- Fixed 302 redirect if empty `redirect_type`
- URL migration from SeoTab is ok now
- Added disabling SeoTab plugin in migration
- Fixed some values in sitemap

All this fixes already inside new release - `3.0.5` in MODX repository

**Comment by joeke** [comment]
Released latest package version 3.1.1 and also tested the mentioned fixes, all seems to be working as expected.
https://modx.com/extras/package/seosuite
