### ISSUE TITLE
Error Page should not have canonical link

### ISSUE THREAD

**Issue by azeller** [Sterc/seosuite#8]
Generally, if [[*id]]==[[++error_page]], the canonical link should not get set. You would therefore be able to create a never-ending stream of self-referencing 404-pages if you post all of those into a forum post and misguide the search engine.

Easy fix for myself, for someone with little SEO knowledge however this might be something they would not want to do.

**Comment by sdrenth** [comment]
@azeller Feel free to submit a Pull Request with the desired changes, we encourage everyone to collaborate and improve all extras together.

**Comment by ilyautkin** [comment]
@azeller https://support.google.com/webmasters/thread/147440368/canonical-tag-404-pages - Canonical tag doesn't matter for Google when a 404 status code is seen. So if you really need this, please make Pull Request - we will discuss this. Now I'm closing issue.
