### ISSUE TITLE
After the installation the modx_seosuite_resource is empty, which makes it look like not working

### ISSUE THREAD

**Issue by dymitar** [Sterc/SEOSuite#83]
After an installation on a live site with hundreds of pages the table modx_seosuite_resource is empty, which makes the tool not usable before you go trough all pages and save them once.
My expectation is the table to be filled with defaults.
To workaround this following SQL can be executed:
```
INSERT INTO `modx_seosuite_resource` (`id`,`keywords`,`resource_id`,`use_default_meta`,`meta_title`,`meta_description`,`index_type`,`follow_type`,`sitemap`,`sitemap_prio`,`sitemap_changefreq`,`canonical`,`canonical_uri`,`editedon`)
  select NULL,"",id,"1","","","1","1","1","normal","weekly","0","",NULL from modx_site_content where id not in (select resource_id from modx_seosuite_resource)
```

**Comment by gitrequests** [comment]
Fixed in https://github.com/Sterc/seosuite/pull/64
